Lungcapacity1<-read.csv("C:\\Users\\user\\Desktop\\Lungcapacity1.csv",header= TRUE,sep=",")
attach(Lungcapacity1)
names(Lungcapacity1)
class(Age)
class(Height)
summary(Height)
help(plot)
?plot
View(Lungcapacity1)

cor(Age,Height)
str(Lungcapacity1)
plot(Age,Height)
plot(Age,Height,main = "Scatterplot",xlab = "Age",ylab = "Height")
plot(Age,Height,main = "Scatterplot",xlab = "Age",ylab = "Height",las=1)



plot(Age,Height,main = "Scatterplot",xlab = "Age",ylab = "Height",las=1,xlim = c(0,30))
plot(Age,Height,main = "Scatterplot",xlab = "Age",ylab = "Height",las=1,xlim = c(0,30),cex=2)
plot(Age,Height,main = "Scatterplot",xlab = "Age",ylab = "Height",las=1,xlim = c(0,25),cex=2,pch =8)
plot(Age,Height,main = "Scatterplot",xlab = "Age",ylab = "Height",las=1,xlim = c(0,25),cex=2,pch=8,col=2)
abline (lm(Height~Age))
abline(lm(Height~Age),col=4)
lines(smooth.spline(Height,Age))
lines(smooth.spline(Height,Age),lty=2,lwd=5)
levels(Smoker)
## linear Regreesion Model
help(lm)
summary(y~X)
Model1<- lm(Lungcap ~ Age+Height)
summary(Model1)
cor(Age,Height,method = "spearman")
confint(Model1,conf.level=0.95)
Model2 <-lm(Lungcap ~ Age+Height+Smoker+Gender+Caresarean)
summary(Model2)
plot(Model2)
x <- c(61.1,61.2,61.8,62.8,63.5,76.1,77,78.1,78.2,78.8,79.7,79.9)
y <- c(16,17,18,19,20,21,22,23,24,25,26,27)
relation <- lm(y~x)
png(file = "linearregression.png")
plot(y,x,col = "blue",main = "Height & Age Regression",abline(lm(x~y)),cex = 2,pch = 16,xlab = "Age ",ylab = "Height")
Model3 <- lm(Lungcap ~ Age+Height)
plot(Model3)
